In [1]:
import numpy as np
import pandas as pd

In [ ]:
Creating DataFrame
#Combining Multiple Series

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28,34,29,42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000,70000,62000,85000]
}

In [7]:
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
column = ['Name', 'Age', 'City', 'Salary']

In [11]:
df[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [ ]:
Create a new Column

In [21]:
df['Designation'] = ['Doctor', 'Engineer', 'Doctor', 'Engineer']

In [13]:
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [22]:
#Remove a Column
df.drop('Designation', axis=1, inplace=True)

In [23]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
df.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [ ]:
Selecting a Row

In [29]:
#For Rows
df.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [30]:
#Selecting Subsets of Rows and Columns
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [31]:
df.loc[[0,1]][['City', 'Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [36]:
df
df.loc[[2,3]][['Name', 'Age']]

    Name  Age
2  Peter   29
3  Linda   42

In [ ]:
Conditional Selection [>, <, <=, >=, ==]

In [42]:
# Select whose age > 30
bool_index = (df['Age'] > 30) & (df['City'] == 'Paris')
df[bool_index]

   Name  Age   City  Salary
1  Anna   34  Paris   70000